initialization
setDefaults
	"Set the default values for theme details"
	self 
		backgroundWidth: 450 px;
		backgroundHeight: 250 px;
		backgroundImageURL: 'http://colourlovers.com.s3.amazonaws.com/images/patterns/3925/3925858.png?1381698366';
		backgroundPadding: 15 px;
		baseFont: 'Ubuntu';
		baseFontFamily: #sansSerif;
	   logoURL: 'http://static.colourlovers.com/images/patternDefinitions/36/368/368247.png?1381699115'